version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "07:15"
      timezone: "Europe/London"
    groups:
      github-actions:
        patterns:
          - "*"
