tap "github/bootstrap"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/formula-analytics"
tap "homebrew/services"
tap "homebrew/test-bot"
brew "git"
brew "go"
brew "imagemagick"
brew "jq"
brew "mas"
brew "shellcheck"
brew "ssh-copy-id"
brew "wget"
brew "nodenv"
brew "vagrant"
cask "caffeine"
cask "viscosity"
cask "alfred"
cask "1password-cli"
cask "docker"
cask "firefox"
cask "google-chrome"
cask "keepingyouawake"
cask "sketch"
cask "transmission"
cask "vagrant"
cask "visual-studio-code"
cask "vmware-fusion"
cask "virtualbox"
cask "amazon-music"
cask "beamer"
cask "tableplus"
cask "the-hit-list"
cask "vlc"
cask "nightowl"
mas "com.agilebits.onepassword7", id: 1333542190
mas "com.apple.dt.Xcode", id: 497799835
mas "com.apple.iMovieApp", id: 408981434
mas "com.apple.iWork.Keynote", id: 409183694
mas "com.apple.iWork.Numbers", id: 409203825
mas "com.apple.iWork.Pages", id: 409201541
