tap "github/bootstrap"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/formula-analytics"
tap "homebrew/services"
tap "homebrew/test-bot"
brew "git"
brew "go"
brew "gnupg"
brew "pinentry-mac"
brew "tree"
brew "imagemagick"
brew "jq"
brew "mas"
brew "shellcheck"
brew "ssh-copy-id"
brew "wget"
brew "nodenv"
brew "packer"
brew "terraform"
cask "vagrant"
cask "sourcetree"
cask "ngrok"
cask "viscosity"
cask "alfred"
cask "docker"
cask "firefox"
cask "google-chrome"
cask "google-chrome-canary"
cask "keepingyouawake"
cask "sketch"
cask "transmission"
cask "vagrant"
cask "visual-studio-code"
cask "virtualbox"
cask "amazon-music"
cask "beamer"
cask "dash"
cask "tableplus"
cask "the-hit-list"
cask "vlc"
cask "nightowl"
cask "calibre"
cask "avibrazil-rdm"
cask "skype"
cask "quicklook-json"
cask "webpquicklook"
mas "com.agilebits.onepassword7", id: 1333542190
mas "com.apple.dt.Xcode", id: 497799835
mas "com.apple.iMovieApp", id: 408981434
mas "com.apple.iWork.Keynote", id: 409183694
mas "com.apple.iWork.Numbers", id: 409203825
mas "com.apple.iWork.Pages", id: 409201541
mas "Magnet", id: 441258766
mas "iWriter Pro", id: 893199093
mas "AntiRSI", id: 442007571
mas "Radium", id: 597611879
cask "1password-cli"
