#!/bin/bash
set -e

if ! [ -L ~/.gnupg ] || ! [ -L ~/.ssh ]
then
  echo "Run script/setup first!" >&2
  exit 1
fi

onepassword_login() {
  if ! command -v op >/dev/null
  then
    echo "Install op first!" >&2
    exit 1
  fi

  # shellcheck disable=SC2154
  if [ -z "$OP_SESSION_wdeboer" ]
  then
    echo "Logging into 1Password..."
    eval "$(op signin my.1password.com weyert@innerfuse.biz)"
  fi
}

onepassword_get() {
  if [ -f "$HOME/$2" ]
  then
    echo "$2 already exists."
    return
  fi
  echo "Extracting $2..."
  onepassword_login
  op get document "$1" > "$HOME/$2"
  chmod 600 "$HOME/$2"
}

onepassword_get ertaghnbg76x4kzt67626f6gze .ssh/id_rsa
onepassword_get 7jmgw5v6lbdxrbrg3enhrhvrlm .ssh/id_rsa_4096
onepassword_get sdhgvti526pgdtblqzqcxs7ugy .ssh/id_rsa_kikkernet
onepassword_get xl4wvg4phnikaxkfqpjhs45wqa .ssh/id_keytree_rsa
onepassword_get nwtahqrzhbamrni64eu2wmql7e .ssh/id_tapico_rsa
onepassword_get hbug3upo2jxbkl3n6njmc4mbyy .gnupg/weyert@innerfuse.biz.private.gpg-key

# License files
if ! [ -f "$HOME/Licenses" ]
then
  echo "Extracting license files..."
  mkdir -p "$HOME/Licenses"
  onepassword_get yx6l3rmdqrg2zfnsrufk7ewvoe "Licenses/Beamer License.beamerlicense"
  onepassword_get mu43sheezbbedozdsbvncz4kfq "Licenses/Weyert de Boer.bettertouchtool"
  onepassword_get zhsgdcadkjc47dfnkgyt3ivdmy "Licenses/license.dash-license"
fi

# Secrets file
if ! [ -f "$HOME/.secrets" ]
then
  echo "Extracting secrets..."
  if ! command -v jq >/dev/null
  then
    echo "Install jq first!" >&2
    exit 1
  fi
  onepassword_login
  GITHUB_TOKEN=$(op get item w3k3s6zgcnhelhc4aimmo6tqsu | jq -r '.details.sections[2].fields[3].v')
  GITLAB_TOKEN=$(op get item 5n7wbhw6hvcyvo3634gbn3ygee | jq -r '.details.sections[1].fields[0].v')
  cat > "$HOME/.secrets" <<EOF
export GITHUB_TOKEN=$GITHUB_TOKEN
export NPM_TOKEN=$GITLAB_TOKEN
EOF
  chmod 600 "$HOME/.secrets"
fi

echo "Storing SSH keys in keychain..."
ssh-add -K

echo "Setting up GPG..."
if ! command -v gpg >/dev/null
then
    echo "Install GPG first!" >&2
    exit 1
fi

chmod 700 ~/.gnupg
gpg --import ~/.gnupg/weyert@innerfuse.biz.public.gpg-key \
             ~/.gnupg/weyert@innerfuse.biz.private.gpg-key
