#!/bin/bash
set -e

if ! [ -L ~/.gnupg ] || ! [ -L ~/.ssh ]
then
  echo "Run script/setup first!" >&2
  exit 1
fi

onepassword_login() {
  if ! command -v op >/dev/null
  then
    echo "Install op first!" >&2
    exit 1
  fi

  # shellcheck disable=SC2154
  if [ -z "$OP_SESSION_wdeboer" ]
  then
    echo "Logging into 1Password..."
    eval "$(op signin my.1password.com weyert@innerfuse.biz)"
  fi
}

onepassword_get() {
  if [ -f "$HOME/$2" ]
  then
    echo "$2 already exists."
    return
  fi
  echo "Extracting $2..."
  onepassword_login
  op get document "$1" > "$HOME/$2"
  chmod 600 "$HOME/$2"
}

onepassword_get ertaghnbg76x4kzt67626f6gze .ssh/id_rsa
onepassword_get sdhgvti526pgdtblqzqcxs7ugy .ssh/id_rsa_kikkernet
onepassword_get xl4wvg4phnikaxkfqpjhs45wqa .ssh/id_keytree_rsa
onepassword_get hbug3upo2jxbkl3n6njmc4mbyy .gnupg/weyert@innerfuse.biz.private.gpg-key

if ! [ -f "$HOME/.secrets" ]
then
  echo "Extracting secrets..."
  if ! command -v jq >/dev/null
  then
    echo "Install jq first!" >&2
    exit 1
  fi
  onepassword_login
  GITHUB_TOKEN=$(op get item amkjxckuo4envfk4vxqinjsgl4 | jq -r '.details.sections[0].fields[].v')
  cat > "$HOME/.secrets" <<EOF
export GITHUB_TOKEN=$GITHUB_TOKEN
EOF
  chmod 600 "$HOME/.secrets"
fi

echo "Storing SSH keys in keychain..."
ssh-add -K

echo "Setting up GPG..."
if ! command -v gpg >/dev/null
then
    echo "Install GPG first!" >&2
    exit 1
fi

chmod 700 ~/.gnupg
gpg --import ~/.gnupg/weyert@innerfuse.biz.public.gpg-key \
             ~/.gnupg/weyert@innerfuse.biz.private.gpg-key
