#!/bin/bash
set -e

echo "Installing Node using Volta"
volta install node@17
volta install node@lts

echo "installing a few global npm packages"
npm install --global serve diff-so-fancy fkill-cli npm-quick-run pnpm

echo "Set the default diff utility for Git"
git config --global core.pager "diff-so-fancy | less --tabs=4 -RFX"
