#!/bin/bash
set -e

echo "Installing ASDF plugins..."
asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git
asdf plugin add golang https://github.com/asdf-community/asdf-golang.git
asdf plugin-add rust https://github.com/code-lever/asdf-rust.git
asdf plugin-add pnpm https://github.com/jonathanmorley/asdf-pnpm.git
asdf plugin-add dotnet-core https://github.com/emersonsoares/asdf-dotnet-core.git
asdf plugin-add direnv
asdf plugin-add dotnet-core https://github.com/emersonsoares/asdf-dotnet-core.git

echo "Install default versions..."
asdf install
