#!/bin/bash
set -e

echo "Installing the node-build-update-defs plugin for nodenv"
$ git clone https://github.com/nodenv/node-build-update-defs.git "$(nodenv root)"/plugins/node-build-update-defs

echo "Installing the lts version of Node and mark it as the default"
eval "$(nodenv init -)"
nodenv install 10.15.3
nodenv global 10.15.3 

echo "Updating the build definitons"
nodenv update-version-defs

echo "Installing the latest stable version of node"
nodenv install 12.3.1