#!/bin/sh
# Run by Strap after installing Brewfile dependencies

cd $(dirname $0)/..

script/install-node
script/extract-onepassword-secrets
script/install-vscode-extensions
script/install-vscode-beta-extensions
script/set-macos-preferences

if [ "$SHELL" != "/bin/zsh" ]
then
  chsh -s /bin/zsh weyertdeboer
fi
