#!/bin/bash
# Run by Strap after installing Brewfile dependencies

cd "$(dirname "$0")/.." || exit

# Close terminal windows on successful exit code
/usr/libexec/PlistBuddy ~/Library/Preferences/com.apple.Terminal.plist -c \
  "Set 'Window Settings':Basic:shellExitAction 1"

# Setup my home directory how I like it
mkdir -pv ~/Development/Projects
mkdir -pv ~/Development/Projects/Personal ~/Development/Projects/Tapico ~/Development/Projects/Work ~/Development/Projects/Opensource
ln -vsf "$(pwd -P)" ~/Development/Projects/Opensource/dotfiles

# Use ZSH as my default Shell
if [ "$SHELL" != "/bin/zsh" ]; then
  chsh -s /bin/zsh weyertdeboer
fi

# Add Github credentials if missing
if command -v "gh" >/dev/null && ! gh auth token &>/dev/null; then
  gh auth login --git-protocol https --hostname github.com --web
fi


# Prepare shell environment
script/install-node
script/extract-onepassword-secrets
script/install-vscode-extensions
script/install-vscode-beta-extensions
script/set-macos-preferences


# Ensure auto-update is always enabled
if [ "$(defaults read /Library/Preferences/com.apple.commerce.plist AutoUpdate)" != "1" ]; then
  sudo defaults write /Library/Preferences/com.apple.commerce.plist AutoUpdate 1
fi

# Enable Touch ID for sudo
bin/touchid-enable-pam-sudo --quiet

# Add GitHub credentials if missing
if command -v "gh" >/dev/null && ! gh auth token &>/dev/null; then
  gh auth login --git-protocol https --hostname github.com --web
fi
